// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxkdixlrhbedhigpehsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a2RpeGxyaGJlZGhpZ3BlaHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzUxNjksImV4cCI6MjA2ODY1MTE2OX0._dwgEq7898BhX_R-v3Aq9bdG__ai1v2wSA2siK2PyvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});